version: '3.8'
services:
  app:
    build:
      context: .
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - XAI_API_KEY=${XAI_API_KEY}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: uvicorn main:app --host 0.0.0.0 --port 8000
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
